export { BLUE_CONTRACTS_RUNTIME_TYPE_REGISTRY as BUILTIN_RUNTIME_TYPE_REGISTRY } from '../registry';

import {
  BLUE_CONTRACTS_RUNTIME_TYPE_REGISTRY,
  BLUE_LANGUAGE_CORE_TYPE_REGISTRY,
} from '../registry';

export const BUILTIN_RUNTIME_TYPE_CONTENT_BY_BLUE_ID = Object.freeze({
  ...BLUE_LANGUAGE_CORE_TYPE_REGISTRY.productionContentByBlueId,
  ...BLUE_CONTRACTS_RUNTIME_TYPE_REGISTRY.productionContentByBlueId,
});

export const BUILTIN_RUNTIME_TYPE_NAME_TO_BLUE_ID_MAP =
  BLUE_CONTRACTS_RUNTIME_TYPE_REGISTRY.productionBlueIdsByName;
