export {
  DEFAULT_WASM_GAS_LIMIT,
  DEFAULT_EXPRESSION_WASM_GAS_LIMIT,
  DEFAULT_JS_STEP_HOST_GAS_LIMIT,
  DEFAULT_EXPRESSION_HOST_GAS_LIMIT,
  WASM_FUEL_PER_HOST_GAS_UNIT,
  hostGasToWasmFuel,
} from '../../runtime/gas-schedule.js';
